BEGIN;

ALTER TABLE grocery_items
    ADD COLUMN IF NOT EXISTS barcode VARCHAR(50),
    ADD COLUMN IF NOT EXISTS source VARCHAR(50),
    ADD COLUMN IF NOT EXISTS nutriscore_grade VARCHAR(5);

ALTER TABLE pantry_items
    ADD COLUMN IF NOT EXISTS barcode VARCHAR(50),
    ADD COLUMN IF NOT EXISTS source VARCHAR(50),
    ADD COLUMN IF NOT EXISTS nutriscore_grade VARCHAR(5);

COMMIT;
